Add a default spec for google-fluentd that turns off build_id generation
GoogleCloudPlatform/google-fluentd pull request #328
Opened 2021-04-15 23:05 UTC by ekund

Add a default spec file to use for google-fluentd.  Created by running `omnibus new google-fluentd --rpm-assets` and taking just the spec file. 
Then, added the one line to remove build_id generation.

2021-04-19 23:39 UTC, igorpeshansky requested changes

2021-04-20 22:33 UTC, ekund commented on resources/google-fluentd/rpm/spec.erb
> +%define _build_id_links none
Can you please clarify what you mean?  The comment refers to the following line.  What are you expecting?

2021-04-20 22:33 UTC, ekund commented on resources/google-fluentd/rpm/spec.erb
> +%define __spec_prep_post true
Fixed.

2021-04-20 23:23 UTC, igorpeshansky commented on resources/google-fluentd/rpm/spec.erb
> +%define _build_id_links none
I meant that the `replace shell actions with 'true'` comment refers to the `%define __spec_… true` lines below, and not to your newly added `%define _build_id_links none` line. But that's been fixed now.

2021-04-20 23:23 UTC, igorpeshansky commented on resources/google-fluentd/rpm/spec.erb
> +<%# pull in the default spec.rb from omnibus %>
Minor nit: it's `spec.erb`.

2021-04-21 15:37 UTC, ekund commented on resources/google-fluentd/rpm/spec.erb
> +<%# pull in the default spec.rb from omnibus %>
done.

2021-04-21 16:02 UTC, igorpeshansky approved these changes
LGTM :shipit:

2021-04-21 17:55 UTC, merged